batch_size: 8
coord_loss_weight_x: 1.0
coord_loss_weight_y: 5.0
clear_exp_checkpoints: true
collision_penalty: true
collision_penalty_factor: 1000
dist_threshold: 0.05
epoch: 100
hf_project_path: kijjjj/test-model1
lr: 1.0e-04
metrics_log_epoch_frequency: 2
mr_threshold: 0.025
optimizer: adamw
push_to_hf: false
step_weights_factor: 1
train_data_dir: csv/train_pre
val_data_dir: csv/val_pre
weight_decay: 0.0001
start_prediction_time: 0.2
is_transformer: true
num_workers: 0
pin_memory: false
gt_vel_movement_threshold: 0.05
vel_loss_weight: 0.5
cls_loss_weight: 0.3
predict_movement_threshold: 0.2
