version: 2

registries:
  pytorch-cu130:
    type: python-index
    url: https://download.pytorch.org/whl/cu130
  ratharog-cumm-spconv:
    type: python-index
    url: https://ratharog.github.io/cumm-spconv/

updates:
  - package-ecosystem: pip
    directory: "/"
    registries:
      - pytorch-cu130
      - ratharog-cumm-spconv
    insecure-external-code-execution: allow
    schedule:
      interval: "monthly"
    groups:
      python-packages:
        patterns:
          - "*"

  - package-ecosystem: pip
    directory: "/.github/workflows/requirements"
    registries:
      - pytorch-cu130
      - ratharog-cumm-spconv
    insecure-external-code-execution: allow
    schedule:
      interval: "monthly"
    groups:
      python-workflow-requirements:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      github-actions-updates:
        patterns:
          - "*"
