attack:
  name: aim_client_response_sniffer

  requirements:
    all:
      - source:
          kind: snapshot
          node_type: rsu
          service_type: aim_server
        verb: exists
      - source:
          kind: snapshot
          node_type: vehicle
          service_type: aim_client
        verb: exists

  start_trigger:
    source:
      kind: snapshot
      node_type: rsu
      service_type: aim_server
      field: tracked_vehicle_count
    verb: increased
    value: 1

  stop_trigger:
    source:
      kind: snapshot
      node_type: rsu
      service_type: aim_server
      field: tracked_vehicle_count
    verb: eq
    value: 0

  targets:
    kind: service_state_field
    source:
      kind: snapshot
      node_type: rsu
      service_type: aim_server
      field: tracked_vehicle_ids
    resolve_to:
      node_type: vehicle
      service_type: aim_client

  stages:
    - id: sniff_aim_client_responses
      type: sniffer
      stage_start_trigger:
        source:
          kind: attack
          attack_name: aim_client_response_sniffer
          field: status
        verb: eq
        value: active
