attack:
  name: aim_server_response_replay

  requirements:
    all:
      - source:
          kind: snapshot
          node_type: rsu
          service_name: aim_server
        verb: exists
      - source:
          kind: snapshot
          node_type: vehicle
          service_name: aim_client
        verb: exists

  start_trigger:
    source:
      kind: snapshot
      node_type: rsu
      service_name: aim_server
      field: tracked_vehicle_count
    verb: increased
    value: 1

  stop_trigger:
    source:
      kind: snapshot
      node_type: rsu
      service_name: aim_server
      field: tracked_vehicle_count
    verb: eq
    value: 0

  targets:
    kind: service_state_field
    source:
      kind: snapshot
      node_type: rsu
      service_name: aim_server
      field: owner_id
    resolve_to:
      node_type: rsu
      service_name: aim_server

  stages:
    - id: replay_aim_server_responses
      type: response_replayer
      stage_stop_trigger:
        source:
          kind: snapshot
          node_type: rsu
          service_name: aim_server
          field: tracked_vehicle_count
        verb: eq
        value: 0
