import torch.nn as nn
import torch.nn.functional as F


class DiscoNetLoss(nn.Module):
    def __init__(self, args):
        super(DiscoNetLoss, self).__init__()
        self.cls_weight = args.get("cls_weight", 1.0)
        self.reg_weight = args.get("reg_weight", 2.0)
        self.kd_weight = args.get("kd_weight", 10.0)

    def forward(self, output_dict, target_dict, teacher_output_dict=None):
        """
        output_dict: the output generated by the DiscoNet model
        target_dict: the ground truth
        teacher_output_dict: the output generated by the Teacher network
        """
        cls_loss = F.binary_cross_entropy_with_logits(output_dict["cls_preds"], target_dict["cls_targets"])
        reg_loss = F.smooth_l1_loss(output_dict["reg_preds"], target_dict["reg_targets"])

        total_loss = self.cls_weight * cls_loss + self.reg_weight * reg_loss

        if teacher_output_dict is not None:
            kd_loss = 0
            layers_to_compare = ["fused_layer", "x_7", "x_6", "x_5"]

            for layer in layers_to_compare:
                student_feat = output_dict[layer]
                teacher_feat = teacher_output_dict[layer]

                s_map = F.log_softmax(student_feat, dim=1)
                t_map = F.softmax(teacher_feat, dim=1)

                kd_loss += F.kl_div(s_map, t_map, reduction="batchmean")

            total_loss += self.kd_weight * kd_loss

        return total_loss
