name: Opencda Tests

on:
  workflow_dispatch:
  pull_request:

jobs:
  pytest:
    uses: CAVISE/pipelines/.github/workflows/python-pytest.yml@main
    with:
      python-versions: '["3.12"]'
      fail-fast: false
      cache-dependency-path: |
        .github/workflows/requirements/requirements-ci.txt
        pyproject.toml
      requirements-file: .github/workflows/requirements/requirements-ci.txt
      matplotlib-backend: Agg
      protobuf-generate: true
      protobuf-source-dir: opencda/core/common/communication/messages
      protobuf-output-dir: opencda/core/common/communication/protos/cavise
      protobuf-messages: '["entity", "opencda", "artery", "capi"]'
      protobuf-mypy-out: true
      pytest-maxfail: 0
      pytest-continue-on-collection-errors: true
      report-dir: reports
      upload-artifact: true
      artifact-name-prefix: pytest-junit
