# Параметры MPC (MPC_XY_Frame.py)
mpc:
  # Конфигурация системы
  system:
    nx: 4                               # Вектор состояния z = [x, y, v, yaw]
    nu: 2                               # Входной вектор u = [acceleration, steer]
    t: 3                                # Горизонт планирования
    t_aug: 30                           # Горизонт для аугментации

  # Конфигурация MPC
  base:
    qf: [5.0, 5.0, 0.0, 20.0]             # целевое состояние
    r: [0.01, 5.8]                        # управление
    rd: [0.01, 10.1]                      # изменение управления

    dist_stop: 1.5                        # Дистанция до цели до остановки (м)
    speed_stop: 0.14                       # Скорость остановки (км/ч)
    time_max: 500.0                       # Максимальное время моделирования
    iter_max: 5                           # Максимальная итерация

    target_speed: 2.8                     # Скорость
    N_IND: 10                             # Поисковый индекс
    dt: 0.1                               # Шаг времени
    d_dist: 1.0                           # Шаг удаления
    du_res: 0.25                          # Порог для остановки итерации

  # Конфигурация ТС
  vehicle:
    rf: 3.3                             # distance from rear to vehicle front end of vehicle (м)
    rb: 0.8                             # istance from rear to vehicle back end of vehicle (м)
    w: 2.4                              # Ширина ТС (м)
    wd: 0.7                             # Дистанция между левым и правым колесов (м)
    wb: 2.5                             # Колесная база (м)
    tr: 0.44                            # Радиус шины (м)
    tw: 0.7                             # Ширина шины (м)
    steer_max: 60.0                    # Максимальный угол поворота (рад)
    steer_change_max: 30.0             # Максимальная скорость угла поворота (°/с)
    speed_max: 15.3                     # Максимальная скорость (м/с)
    speed_min: -5.5                     # Минимальная скорость (км/ч)
    acceleration_max: 1.0               # Максимальное ускорение (м/с²)
